### PR TITLE
add travis integration to build docker image

### PR DESCRIPTION
**Pull request by drgarcia1986**
(we need to activate Travis integration and configure the env-vars)

### CODE REVIEW

**Comment by yagonobre** [comment]
please run `chmod +x .ci-docker.sh`

**Comment by drgarcia1986** [comment]
@yagonobre done 👍

**Review by yagonobre — APPROVED** [review]
LGTM

**Comment by drgarcia1986** [comment]
Travis already configured

**Review by arnaldopereira — APPROVED** [review]

**Pull request merged**
